apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHZxaXd1b3Fr
  CLOUDINARY_KEY: NTY5ODQ3MTE0NjIzNTYz
  CLOUDINARY_SECRET: TEJ5SFNuRnBxaGZuRXhQMzZKNk1kMmx4ZGRv
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZMmhoYm1Sb1lXNWhNalFpTENKaElqb2lZMjF0WlhGM09EWTJNREJqT1RKeGN6QTRaR2t3YlhSNVl5SjkuYmVidW8tSmdzeGpfZnFxSl96NVhkQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9jaGFuZGFuYWRhc2FyaTM0X2RiX3VzZXI6VmFPMm40SG82aXJsSlNuZUBjbHVzdGVyMC5neDZldmE0Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
  SECRET: Y2hhbmRodQ==
